export {
  CURRENT_SCHEMA_VERSION,
  AssetSchema,
  ClipSchema,
  ProjectSchema,
  TrackSchema,
  parseProject,
  createEmptyProject,
  type Asset,
  type AudioClip,
  type Clip,
  type OverlayClip,
  type Project,
  type ProjectSettings,
  type TextClip,
  type TextStyle,
  type Track,
  type Transform2D,
  type VideoClip,
} from './project';
